#!/usr/bin/env bash

/Users/ibrahim/scripts/declutter.py
notifier=/usr/local/bin/terminal-notifier

$notifier -title Declutter -subtitle "Daily Updated" -message "Completed"
now=$(date)
echo "Cron job update completed at $now"
