#!/usr/bin/env bash
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        python3 $(locate declutter.py)
elif [[ "$OSTYPE" == "darwin"* ]]; then
	files=$(python3 $(locate declutter.py))
	echo $files
	terminal-notifier -title Declutter -subtitle "Deleted Files:" -message "$files"
fi
rm ~/Downloads/*.docx ~/Downloads/*.pptx ~/Downloads/*.xlsx
